manifest:
  version: "1.2"

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 1f6485eca25431b5ff27ce9a754218c9e559bbbb
      path: zephyr
      import:
        path-prefix: west
        name-allowlist:
          - cmsis
          - cmsis_6
    - name: zephyr-lang-rust
      remote: zephyrproject-rtos
      revision: dd73abc242e995784da62352fe8c70d9a6c7ac2e
      path: west/modules/lang/rust

  self:
    path: manifest
