CONFIG_CONSOLE=n
CONFIG_COMMON_LIBC_MALLOC=n
CONFIG_DISPLAY=y
CONFIG_DMA=y
CONFIG_ESP_APPCPU_DRAM_SIZE=0x6000
CONFIG_ESP_APPCPU_IRAM_SIZE=0x6000
CONFIG_ESPTOOLPY_FLASHMODE_QIO=y
CONFIG_GPIO=y
CONFIG_HEAP_MEM_POOL_SIZE=1024
CONFIG_IPM=y
CONFIG_LOG=n
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_MP_MAX_NUM_CPUS=2
CONFIG_RUST=y
CONFIG_RUST_ALLOC=y
CONFIG_TICKLESS_KERNEL=n
CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000
