CONFIG_CONSOLE=n
CONFIG_BOOT_BANNER=n
CONFIG_PRINTK=n
CONFIG_EXCEPTION_DEBUG=n
CONFIG_COMMON_LIBC_MALLOC=n
CONFIG_DISPLAY=y
CONFIG_DMA=y
CONFIG_ESP_APPCPU_DRAM_SIZE=0x4600
CONFIG_ESP_APPCPU_IRAM_SIZE=0x4200
CONFIG_ESPTOOLPY_FLASHMODE_QIO=y
CONFIG_GPIO=y
CONFIG_HEAP_MEM_POOL_SIZE=1024
CONFIG_IPM=y
CONFIG_IDLE_STACK_SIZE=1024
CONFIG_LOG=n
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_MCUBOOT_EXTRA_IMGTOOL_ARGS="--slot-size 0x300000"
CONFIG_MP_MAX_NUM_CPUS=2
CONFIG_RUST=y
CONFIG_RUST_ALLOC=y
CONFIG_SYS_CLOCK_EXISTS=y
CONFIG_XTENSA_TIMER=y
CONFIG_XTENSA_TIMER_ID=1
CONFIG_TICKLESS_KERNEL=n
CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000
