CONFIG_CONSOLE=n
CONFIG_DISPLAY=y
CONFIG_DMA=y
CONFIG_GPIO=y
CONFIG_HEAP_MEM_POOL_SIZE=65536
CONFIG_IPM=y
CONFIG_LOG=n
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_MP_MAX_NUM_CPUS=2
CONFIG_RUST=y
CONFIG_RUST_ALLOC=y
