// SPDX-License-Identifier: GPL-3.0-only

export component RendererWindow inherits Window {
    width: 320px;
    height: 240px;
    in-out property <int> frame: 0;
    background: #11263d;

    Rectangle {
        x: (240 - Math.abs(Math.mod(root.frame, 480) - 240)) * 1px;
        y: (160 - Math.abs(Math.mod(root.frame, 320) - 160)) * 1px;
        width: 80px;
        height: 80px;
        background: #f2c14e;
    }
}
