CONFIG_CONSOLE=y
CONFIG_ESP_SPIRAM=y
CONFIG_ESPTOOLPY_FLASHMODE_QIO=y
CONFIG_ESP_SPIRAM_HEAP_SIZE=0
CONFIG_ESP_SPIRAM_MEMTEST=n
CONFIG_SPIRAM_SPEED_80M=y
CONFIG_GPIO=y
CONFIG_IPM=y
CONFIG_LOG=n
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_PRINTK=n
CONFIG_REGULATOR=y
CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=y
