# SPDX-License-Identifier: GPL-3.0-only

CONFIG_DISPLAY=y
CONFIG_ESP_SPIRAM=y
CONFIG_ESP_SPIRAM_MEMTEST=y
CONFIG_HEAP_MEM_POOL_SIZE=131072
CONFIG_INPUT=y
CONFIG_LOG=y
CONFIG_LOG_BACKEND_RTT=n
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_RUST=y
CONFIG_RUST_ALLOC=y
